name: Ubuntu Latest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make with gcc
      run: make CC=gcc
    - name: run tests
      run: make check
    - name: clean
      run: make clean
    - name: make with clang
      run: make CC=clang
    - name: run tests
      run: make check